openTickets: false,
            closedTickets: false,
            createTicket: false,
            updateTicket: false,
            searchTerm: '',
            tickets: [],
            ticket: {},
            ticketCounts: [],